### ISSUE TITLE
Stack trace

### ISSUE THREAD

**Issue by Pangamma** [Gamealition/GPrism#25] opened 2017-08-19 20:26 UTC
19.08 13:25:31 [Server] INFO [Prism]: Database connection error: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'blocklogging.prism_10_data.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
19.08 13:25:31 [Server] WARN com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'blocklogging.prism_10_data.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
19.08 13:25:31 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
19.08 13:25:31 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
19.08 13:25:31 [Server] WARN at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
19.08 13:25:31 [Server] WARN at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
19.08 13:25:31 [Server] WARN at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
19.08 13:25:31 [Server] WARN at com.mysql.jdbc.Util.getInstance(Util.java:408)
19.08 13:25:31 [Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
19.08 13:25:31 [Server] WARN at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
19.08 13:25:31 [Server] WARN at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
19.08 13:25:31 [Server] WARN at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
19.08 13:25:31 [Server] WARN at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
19.08 13:25:31 [Server] WARN at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2494)
19.08 13:25:31 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
19.08 13:25:31 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1966)
19.08 13:25:31 [Server] WARN at me.botsko.prism.actionlibs.ActionsQuery.lookup(ActionsQuery.java:121)
19.08 13:25:31 [Server] WARN at me.botsko.prism.actionlibs.ActionsQuery.lookup(ActionsQuery.java:63)
19.08 13:25:31 [Server] WARN at me.botsko.prism.wands.InspectorWand$1.run(InspectorWand.java:104)
19.08 13:25:31 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
19.08 13:25:31 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
19.08 13:25:31 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
19.08 13:25:31 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
19.08 13:25:31 [Server] WARN at java.lang.Thread.run(Thread.java:745)
19.08 13:25:31 [Server] INFO [Prism]: Database connection error: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'blocklogging.prism_10_data.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
19.08 13:25:31 [Server] WARN com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'blocklogging.prism_10_data.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
19.08 13:25:31 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
19.08 13:25:31 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
19.08 13:25:31 [Server] WARN at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
19.08 13:25:31 [Server] WARN at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
19.08 13:25:31 [Server] WARN at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
19.08 13:25:31 [Server] WARN at com.mysql.jdbc.Util.getInstance(Util.java:408)
19.08 13:25:31 [Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
19.08 13:25:31 [Server] WARN at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
19.08 13:25:31 [Server] WARN at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
19.08 13:25:31 [Server] WARN at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
19.08 13:25:31 [Server] WARN at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
19.08 13:25:31 [Server] WARN at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2494)
19.08 13:25:31 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
19.08 13:25:31 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1966)
19.08 13:25:31 [Server] WARN at me.botsko.prism.actionlibs.ActionsQuery.lookup(ActionsQuery.java:121)
19.08 13:25:31 [Server] WARN at me.botsko.prism.actionlibs.ActionsQuery.lookup(ActionsQuery.java:63)
19.08 13:25:31 [Server] WARN at me.botsko.prism.wands.InspectorWand$1.run(InspectorWand.java:104)
19.08 13:25:31 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
19.08 13:25:31 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
19.08 13:25:31 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
19.08 13:25:31 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
19.08 13:25:31 [Server] WARN at java.lang.Thread.run(Thread.java:745)
19.08 13:25:32 [Server] INFO [Prism]: Database connection error: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'blocklogging.prism_10_data.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
19.08 13:25:32 [Server] WARN com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'blocklogging.prism_10_data.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
19.08 13:25:32 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
19.08 13:25:32 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
19.08 13:25:32 [Server] WARN at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
19.08 13:25:32 [Server] WARN at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
19.08 13:25:32 [Server] WARN at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
19.08 13:25:32 [Server] WARN at com.mysql.jdbc.Util.getInstance(Util.java:408)
19.08 13:25:32 [Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
19.08 13:25:32 [Server] WARN at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
19.08 13:25:32 [Server] WARN at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
19.08 13:25:32 [Server] WARN at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
19.08 13:25:32 [Server] WARN at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
19.08 13:25:32 [Server] WARN at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2494)
19.08 13:25:32 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
19.08 13:25:32 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1966)
19.08 13:25:32 [Server] WARN at me.botsko.prism.actionlibs.ActionsQuery.lookup(ActionsQuery.java:121)
19.08 13:25:32 [Server] WARN at me.botsko.prism.actionlibs.ActionsQuery.lookup(ActionsQuery.java:63)
19.08 13:25:32 [Server] WARN at me.botsko.prism.wands.InspectorWand$1.run(InspectorWand.java:104)
19.08 13:25:32 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
19.08 13:25:32 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
19.08 13:25:32 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
19.08 13:25:32 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
19.08 13:25:32 [Server] WARN at java.lang.Thread.run(Thread.java:745)

**Comment by RoyCurtis** [comment] 2017-08-19 21:17
Duplicate of #3 ; sorry for not having fixed this yet. Follow this comment for a solution: https://github.com/Gamealition/GPrism/issues/3#issuecomment-298180213

**Closed as completed by RoyCurtis** 2017-08-19 21:17 UTC
Labels: duplicate
